# Core Split Configuration
CONFIG_ZMK_SPLIT=y

# Overrides to block central settings from bleeding in
CONFIG_ZMK_USB=n
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Core Input Pipelines
CONFIG_SPI=y                    
CONFIG_INPUT=y                   
CONFIG_ZMK_POINTING=y

# Activate Badjeff's Driver Engine
CONFIG_PMW3610_ALT=y

# Stability Overrides for Wireless Hardware Execution
CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=20
CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=1000
